apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: maritime
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp2          # AWS EKS default EBS storage class
  resources:
    requests:
      storage: 10Gi
